### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by metanav** [sefr-classifier/sefr#4]
In the README it says "The data should be normalized in the range [0, n]". What is n here? I am using Standard deviation, RMS etc. as features. Do I need to normalize?

**Comment by hamidkm9** [comment]
n is any positive number. You can set it to 1 or 100. The point is that you do not have any negative values in your data.

**Comment by farooqkz** [comment]
I believe this can be closed and for the discussions, there is a dedicated feature in Github
