### ISSUE TITLE
Why the bias is positive?

### ISSUE THREAD

**Issue by Grabber** [sefr-classifier/sefr#5]
Derivating from the hyperplane equation:

```
wT*x + b <= 0
wT*x <= -b
```

So, why the bias isn't negative here?
https://github.com/sefr-classifier/sefr/blob/2abe67d2cbbfa3445cdd0e61ed7a9408a096f8d6/SEFR.py#L75

**Comment by sefr-classifier** [comment]
> 
That's just a convention. You can edit the formula of bias calculation and then make it negative here.
